server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: 'enquete'
  main:
    allow-bean-definition-overriding: true     
  mail:
    host: smtp.gmail.com
    port: 587
    username: poc.enquete.cielo@gmail.com
    password: C1elo2020
    protocol: smtp
    properties:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
    
hystrix:
  shareSecurityContext: true